{{ if gt (len .Values.yaraRules) 0 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "clamav.yararulesname" . }}
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
data:
{{- range .Values.yaraRules }}
  {{ .name }}: |-
    {{- .rule | nindent 4 }}
{{- end }}
{{- end }}
