{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "clamav.configname" . }}
  labels:
    {{- include "clamav.labels" . | nindent 4 }}
data:
{{- with .Values.config }}
  clamd.conf: |-
    {{- (tpl . $root) | nindent 4 }}
{{- end }}

{{- if .Values.freshclam.enabled }}
{{- with .Values.freshclam.config }}
  freshclam.conf: |-
    {{- (tpl . $root) | nindent 4 }}
{{- end }}
{{- end }}
