apiVersion: v1
name: influxdb
version: 5.0.0
appVersion: 1.8.10
description: Scalable datastore for metrics, events, and real-time analytics.
keywords:
  - influxdb
  - database
  - timeseries
  - influxdata
home: https://www.influxdata.com/time-series-platform/influxdb/
sources:
  - https://github.com/influxdata/influxdb
maintainers:
  - name: wiseman13
    email: scott.wise@proagrica.com
  - name: secarar
    email: robert.secara@proagrica.com
engine: gotpl
