name: GitHub Workflow Test

on:
  pull_request:
    paths:
      - ".github/workflows/workflow-test.yaml"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v2.1
        with:
          version: latest

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (lint)
        run: ct lint --all --config ct.yaml

      - name: Create Kind cluster
        uses: helm/kind-action@v1.8.0

      - name: Run chart-testing (install)
        run: ct install --all --config ct.yaml
